### ISSUE TITLE
如何限制ES服务的内存使用

### ISSUE THREAD

**Issue by WGrape** [WGrape/sparrow#18]
在docker-compose文件中加入以下配置即可

```
    deploy:
      resources:
        limits:
          memory: 2G
```

<img width="630" alt="image" src="https://github.com/user-attachments/assets/2298bc19-07a7-4975-ace8-81eb19e96c44">
